version: '3.8'

services:
  tn-calc-back-api:
    image: node:18
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PORT: 3000
    volumes:
      - ../:/workspace/
    ports:
      - 3000:3000
    working_dir: /workspace
    command: yarn start:dev
    healthcheck:
      test: node src/healthcheck.js
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s


  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tncalc

volumes:
  postgres-data:
